//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_EVALUACIONPARAMETRO
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public Nullable<decimal> ID_PARAMETRO { get; set; }
        public Nullable<decimal> ID_EVALUACION { get; set; }
        public Nullable<short> APRUEBA { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual SSF_EVALUACION SSF_EVALUACION { get; set; }
        public virtual SSF_PARAMETRO SSF_PARAMETRO { get; set; }
    }
}
