//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_USUARIO
    {
        public SSF_USUARIO()
        {
            this.SSF_ATENCIONMEDICA = new HashSet<SSF_ATENCIONMEDICA>();
            this.SSF_CAPACITACIONEMPRESA = new HashSet<SSF_CAPACITACIONEMPRESA>();
            this.SSF_FICHAMEDICA = new HashSet<SSF_FICHAMEDICA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string USERNAME { get; set; }
        public string CONTRASENA { get; set; }
        public decimal ID_PERSONA { get; set; }
        public decimal ID_PERFIL { get; set; }
        public Nullable<decimal> ID_EMPRESA { get; set; }
    
        public virtual ICollection<SSF_ATENCIONMEDICA> SSF_ATENCIONMEDICA { get; set; }
        public virtual ICollection<SSF_CAPACITACIONEMPRESA> SSF_CAPACITACIONEMPRESA { get; set; }
        public virtual SSF_EMPRESA SSF_EMPRESA { get; set; }
        public virtual ICollection<SSF_FICHAMEDICA> SSF_FICHAMEDICA { get; set; }
        public virtual SSF_PERFIL SSF_PERFIL { get; set; }
        public virtual SSF_PERSONA SSF_PERSONA { get; set; }
    }
}
