//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_EVALUACIONTIPO
    {
        public SSF_EVALUACIONTIPO()
        {
            this.SSF_EVALUACION = new HashSet<SSF_EVALUACION>();
            this.SSF_PARAMETRO = new HashSet<SSF_PARAMETRO>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<SSF_EVALUACION> SSF_EVALUACION { get; set; }
        public virtual ICollection<SSF_PARAMETRO> SSF_PARAMETRO { get; set; }
    }
}
