//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_ATENCIONMEDICA
    {
        public SSF_ATENCIONMEDICA()
        {
            this.SSF_ADJUNTO = new HashSet<SSF_ADJUNTO>();
            this.SSF_FICHAMEDICAATENCION = new HashSet<SSF_FICHAMEDICAATENCION>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public Nullable<decimal> ID_MEDICO { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<SSF_ADJUNTO> SSF_ADJUNTO { get; set; }
        public virtual ICollection<SSF_FICHAMEDICAATENCION> SSF_FICHAMEDICAATENCION { get; set; }
        public virtual SSF_MEDICO SSF_MEDICO { get; set; }
        public virtual SSF_USUARIO SSF_USUARIO { get; set; }
    }
}
