//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_PERFIL
    {
        public SSF_PERFIL()
        {
            this.SSF_USUARIO = new HashSet<SSF_USUARIO>();
            this.SSF_PERFILVISTA = new HashSet<SSF_PERFILVISTA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string PERFIL { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<SSF_USUARIO> SSF_USUARIO { get; set; }
        public virtual ICollection<SSF_PERFILVISTA> SSF_PERFILVISTA { get; set; }
    }
}
