//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_MEDICOESPECIALIDAD
    {
        public SSF_MEDICOESPECIALIDAD()
        {
            this.SSF_MEDICO = new HashSet<SSF_MEDICO>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string ESPECIALIDAD { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<SSF_MEDICO> SSF_MEDICO { get; set; }
    }
}
