//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_EXAMEN
    {
        public SSF_EXAMEN()
        {
            this.SSF_FICHAMEDICA = new HashSet<SSF_FICHAMEDICA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public decimal ID_EXAMENTIPO { get; set; }
        public string EXAMEN { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual SSF_EXAMENTIPO SSF_EXAMENTIPO { get; set; }
        public virtual ICollection<SSF_FICHAMEDICA> SSF_FICHAMEDICA { get; set; }
    }
}
