//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_MEDICO
    {
        public SSF_MEDICO()
        {
            this.SSF_ATENCIONMEDICA = new HashSet<SSF_ATENCIONMEDICA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public decimal ID_ESPECIALIDAD { get; set; }
        public decimal ID_CENTROMEDICO { get; set; }
    
        public virtual ICollection<SSF_ATENCIONMEDICA> SSF_ATENCIONMEDICA { get; set; }
        public virtual SSF_CENTROMEDICO SSF_CENTROMEDICO { get; set; }
        public virtual SSF_MEDICOESPECIALIDAD SSF_MEDICOESPECIALIDAD { get; set; }
    }
}
