//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_PERSONA
    {
        public SSF_PERSONA()
        {
            this.SSF_ALUMNO = new HashSet<SSF_ALUMNO>();
            this.SSF_USUARIO = new HashSet<SSF_USUARIO>();
        }
    
        public decimal ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string CORREO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA_NAC { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
    
        public virtual ICollection<SSF_ALUMNO> SSF_ALUMNO { get; set; }
        public virtual ICollection<SSF_USUARIO> SSF_USUARIO { get; set; }
    }
}
