//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_CAPACITACIONEMPRESA
    {
        public SSF_CAPACITACIONEMPRESA()
        {
            this.SSF_ALUMNOCAPAEMPRESA = new HashSet<SSF_ALUMNOCAPAEMPRESA>();
            this.SSF_CAPACITACIONDIA = new HashSet<SSF_CAPACITACIONDIA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public Nullable<decimal> ID_CAPACITACION { get; set; }
        public Nullable<decimal> ID_EMPRESA { get; set; }
        public Nullable<decimal> ID_ESTADOCAPACITACION { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public Nullable<int> CANTIDAD_ALUMNOS { get; set; }
    
        public virtual ICollection<SSF_ALUMNOCAPAEMPRESA> SSF_ALUMNOCAPAEMPRESA { get; set; }
        public virtual SSF_CAPACITACION SSF_CAPACITACION { get; set; }
        public virtual ICollection<SSF_CAPACITACIONDIA> SSF_CAPACITACIONDIA { get; set; }
        public virtual SSF_USUARIO SSF_USUARIO { get; set; }
        public virtual SSF_EMPRESA SSF_EMPRESA { get; set; }
        public virtual SSF_ESTADOCAPAEMPRESA SSF_ESTADOCAPAEMPRESA { get; set; }
    }
}
