//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_VISTA
    {
        public SSF_VISTA()
        {
            this.SSF_PERFILVISTA = new HashSet<SSF_PERFILVISTA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string NOMBRE { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> ID_MENU { get; set; }
    
        public virtual SSF_MENU SSF_MENU { get; set; }
        public virtual ICollection<SSF_PERFILVISTA> SSF_PERFILVISTA { get; set; }
    }
}
