//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_CAPACITACION
    {
        public SSF_CAPACITACION()
        {
            this.SSF_CAPACITACIONEMPRESA = new HashSet<SSF_CAPACITACIONEMPRESA>();
            this.SSF_CERTIFICADO = new HashSet<SSF_CERTIFICADO>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> HORAS { get; set; }
        public Nullable<decimal> ID_CAPACITACIONTIPO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
    
        public virtual SSF_CAPACITACIONTIPO SSF_CAPACITACIONTIPO { get; set; }
        public virtual ICollection<SSF_CAPACITACIONEMPRESA> SSF_CAPACITACIONEMPRESA { get; set; }
        public virtual ICollection<SSF_CERTIFICADO> SSF_CERTIFICADO { get; set; }
    }
}
