//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF_PARAMETRO
    {
        public SSF_PARAMETRO()
        {
            this.SSF_EVALUACIONPARAMETRO = new HashSet<SSF_EVALUACIONPARAMETRO>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECH_CREACION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public string PARAMETRO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_EVALUACIONTIPO { get; set; }
    
        public virtual ICollection<SSF_EVALUACIONPARAMETRO> SSF_EVALUACIONPARAMETRO { get; set; }
        public virtual SSF_EVALUACIONTIPO SSF_EVALUACIONTIPO { get; set; }
    }
}
